FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

RUN apk add --no-cache nginx

RUN mkdir -p /var/www/html
RUN cp -r /app/dist/* /var/www/html/

COPY nginx.conf /etc/nginx/http.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
